### PR TITLE
修复web界面vc模式不能用问题。改拼写错误、给字符串前加f标

### PR DESCRIPTION
**Pull request by kslz**
警惕错别字问题，警钟敲烂

### CODE REVIEW

**Comment by benny1227** [comment]
image

**Comment by kslz** [comment]
> image

你把app_vc.py文件发我看下

**Comment by benny1227** [comment]
[app_vc.zip](https://github.com/babysor/MockingBird/files/10121971/app_vc.zip)

**Comment by kslz** [comment]
> [app_vc.zip](https://github.com/babysor/MockingBird/files/10121971/app_vc.zip)

app_vc.py是python文件啊 你给我的是HTML

**Comment by benny1227** [comment]
sorry，浪费您时间，刚才搞错了。我覆盖了app_vc修正。但是但现在还是有空字节错误提示
image

**Comment by kslz** [comment]
> sorry，浪费您时间，刚才搞错了。我覆盖了app_vc修正。但是但现在还是有空字节错误提示 image

无妨 你截一下黑窗口里的报错我看下

**Comment by benny1227** [comment]
File "C:\Users\admin\anaconda3\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 564, in _run_script
    exec(code, module.__dict__)
File "C:\Users\admin\AppData\Local\Temp\tmp3j0w564f.py", line 14, in <module>
    render_streamlit_ui()
File "E:\MockingBird-main\mkgui\base\ui\streamlit_ui.py", line 841, in render_streamlit_ui
    opyrator = getOpyrator(mode)
File "E:\MockingBird-main\mkgui\base\ui\streamlit_ui.py", line 810, in getOpyrator
    from mkgui.app_vc import convert
File "E:\MockingBird-main\mkgui\app_vc.py", line 8, in <module>
    import ppg_extractor as Extractor
File "E:\MockingBird-main\ppg_extractor\__init__.py", line 8, in <module>
    from .encoder.conformer_encoder import ConformerEncoder
File "E:\MockingBird-main\ppg_extractor\encoder\conformer_encoder.py", line 28, in <module>
    from .subsampling import Conv2dNoSubsampling, Conv2dSubsampling
File "E:\MockingBird-main\ppg_extractor\encoder\subsampling.py", line 11, in <module>
    from espnet.nets.pytorch_backend.transformer.embedding import PositionalEncoding

**Comment by kslz** [comment]
> import ppg_extractor as Extractor

根据我粗浅的python理解应该是【import ppg_extractor as Extractor】import这句都出错了，得作者看下了，不过应该和我这次的pr不相关

**Pull request merged**
